{{-- Cover block: title, scope line, generated-by stamp. Expects $title, $scope, $userName. --}}
<h1>{{ $title }}</h1>
<p class="scope">{{ $scope }}<br>Generated by {{ $userName }} · {{ now()->format('M j, Y H:i') }}</p>
